spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: fool5788
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8765
      filter:
        # 打开/关闭对 spring MVC 端点的保护
        enabled: true
    nacos:
      discovery:
        # nacos 服务发现地址
        server-addr: localhost:8848
#    stream:
#      rocketmq:
#        binder:
#          name-server: localhost:9876
#      bindings:
#        output:
#          # 指定 topic
#          destination: test-topic

server:
  port: 8030
ribbon:
  eager-load:
    enabled: true
    # 启用饥饿加载，减少第一次访问的响应时间。多个服务名用,分隔
    clients: user-center


management:
  endpoints:
    web:
      exposure:
        include: '*'

# 整合 Feign 和 Sentinel
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: basic

rocketmq:
  name-server: localhost:9876
  producer:
    group: test-group

